version: '3.9'

services:
  web:
    build: .
    container_name: app_web
    ports:
      - "8088:8088"  # ajuste conforme sua aplicação (ex: Flask ou FastAPI)
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=estoque_bebidas_db
    volumes:
      - .:/estoque_bebidas

  db:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: estoque_bebidas_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
