# Generated by Django 5.2.1 on 2025-07-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimentaçãoestoque_lote_produto_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='volumetria',
            field=models.CharField(choices=[('Caixa', 'Caixa'), ('Garrafa', 'Garrafa'), ('Lata', 'Lata'), ('Barril', 'Barril'), ('Outros', 'Outros')], default='Garrafa', max_length=20),
        ),
    ]
