# Generated by Django 5.2.1 on 2025-07-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_volumetria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='movimentaçãoestoque',
            name='id_produto',
        ),
        migrations.RemoveField(
            model_name='movimentaçãoestoque',
            name='lote',
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('quantidade', models.IntegerField(default=0)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.produto')),
            ],
            options={
                'db_table': 'lote',
                'unique_together': {('id_produto', 'numero_lote')},
            },
        ),
        migrations.AddField(
            model_name='movimentaçãoestoque',
            name='id_lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lote'),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='lote',
        ),
    ]
