# Generated by Django 5.2.1 on 2025-07-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Alimentos', 'Alimentos'), ('Utensilios', 'Utensílios'), ('Suprimentos', 'Suprimentos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='volumetria',
            field=models.CharField(choices=[('Caixa', 'Caixa'), ('Saco', 'Saco'), ('Unidade', 'Unidade'), ('Pacote', 'Pacote'), ('Outros', 'Outros')], default='Pacote', max_length=20),
        ),
    ]
