# Generated by Django 5.2.1 on 2025-07-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_categoria_alter_produto_volumetria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
